# Generated by Django 3.2.8 on 2021-11-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='movie',
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
